# Generated by Django 2.1.1 on 2019-01-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bovino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=255, unique=True, verbose_name='Brinco')),
                ('peso', models.DecimalField(decimal_places=4, help_text="<p class='comment'>Utilize vírgula caso necessário</p>", max_digits=40, verbose_name='Peso em Kg')),
                ('nascimento', models.DateField(help_text="<p class='comment'>Escreva no seguinte formato: <em>DD/MM/AAAA</em></p>", verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Gênero')),
                ('foto', models.FileField(blank=True, null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
            ],
        ),
        migrations.CreateModel(
            name='Filhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filhos', models.ManyToManyField(blank=True, help_text="<p class='comment'>Use CTRL para selecionar mais de um, ou deixar de selecionar um.</p>", null=True, to='animais.Bovino')),
            ],
        ),
        migrations.AddField(
            model_name='bovino',
            name='filho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animais.Filhos'),
        ),
    ]
