# Generated by Django 2.1.1 on 2019-01-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bovino',
            name='foto',
        ),
        migrations.AddField(
            model_name='bovino',
            name='foto_dois',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Segunda Foto'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='foto_quatro',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Quarta Foto'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='foto_tres',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Terceira Foto'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='foto_um',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Principal'),
        ),
    ]
