# Generated by Django 2.1.1 on 2019-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_auto_20190112_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bovino',
            name='peso',
            field=models.TextField(verbose_name='Peso em Kg e sua Data'),
        ),
    ]
