# Generated by Django 2.1.1 on 2019-01-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_auto_20190115_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='medicamento',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamento e sua Data de aplicação'),
        ),
    ]
