# Generated by Django 2.1.1 on 2019-01-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_bovino_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='tipo',
            field=models.CharField(choices=[('Cria', 'Bovino de Cria'), ('Engorda', 'Bovino de Engorda')], default='Cria', max_length=10, verbose_name='Tipo'),
        ),
    ]
