# Generated by Django 2.1.1 on 2019-01-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0007_bovino_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='estado',
            field=models.CharField(choices=[('Possui', 'Possui'), ('Vendiddo', 'Vendido'), ('Morto', 'Morto')], default='Possui', max_length=10, verbose_name='Estado'),
        ),
    ]
